accounts/urls.py
from django.urls import path

from . import views

app_name='accounts'

urlpatterns= [
    path('registerAsUser', views.registerAsUser, name='registerAsUser'),
    path('loginAsUser', views.loginAsUser, name='loginAsUser'),

    path('userprofile', views.UserProfile, name='UserProfile'),


    path('registerAsVenue', views.registerAsVenue, name='registerAsVenue'),    
    path('venueRegistrationSubmitted', views.venueRegistrationSubmitted, name='venueRegistrationSubmitted'),   

    path('logout', views.logoutUser, name="logout"),
    path("success", views.success, name="success"),

]

booking/urls.py
from django.urls import path

from . import views
# namespace
app_name='booking'

urlpatterns= [
    path('mybookings', views.Mybookings, name='Mybookings'),
    path("esewa-verify/", views.EsewaVerifyView, name="esewaverify"),
]

home/urls.py
from django.urls import path

from . import views

app_name='home'

urlpatterns= [
    path('', views.index, name='index'),
    path('search', views.search, name="search"),
]

venbook/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.contrib.auth import views as auth_views

from booking import views as bookingView
from accounts import views as accountsView
from venue import views as venueView


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('social_login/', include('allauth.urls')),
    path('venue/',include('venue.urls')),
    path('events/',include('events.urls')),
    path('calender/',include('calender.urls')),
    path('bookings/',include('booking.urls')),

    path('SendRequestUpdate/',bookingView.SendRequestUpdate,name="SendRequestUpdate"),
    path('Cancelbooking/',bookingView.Cancelbooking,name="Cancelbooking"),

    path('AddReview/',venueView.AddReview,name="AddReview"),


    path("EsewaRequestView/", bookingView.EsewaRequestView, name="EsewaRequestView"),


    path("AddUserInfo/", accountsView.AddUserInfo, name="AddUserInfo"),
    path("UpdateUserInfo/", accountsView.UpdateUserInfo, name="UpdateUserInfo"),


    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
        name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), 
        name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),


    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

venue/urls.py
from django.urls import include, path

from . import views


app_name='venue'


urlpatterns= [
    path('venuedisplay', views.VenueDisplay, name='VenueDisplay'),
    path('dashboard/<int:id>', views.VenueEdit, name='VenueEdit'),
    path('updatevenueprice/', views.VenuePriceUpdate, name='VenuePriceUpdate'),
    path('updatevenuedesc/<int:id>', views.VenueDescUpdate, name='VenueDescUpdate'),
    path('venuedetail/<int:id>',views.VenueDetail,name="VenueDetail"),
    path('booking-request/',views.BookingRequest,name="BookingRequest"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from accounts.models import VenueAccount, is_verified

# Create your views here.
def index(request):
    return render(request,'home/index.html')


def search(request):
    query=request.GET['location']
    allPosts = is_verified.objects.filter(verified = True, venue_account__city__icontains=query)
    params={
        'allPosts': allPosts
        }   
    return render(request, 'venue/displaypage.html', params)

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/base.css' %}">
    <link rel="stylesheet" href="{% static 'venue/displaypage.css' %}">

    <script type="text/javascript" src="{% static 'venue/jquery-3.6.0.js' %}"></script> 
    <script type="text/javascript" src="{% static 'venue/jquery.easing.min.js' %}"></script> 

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
    integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
    crossorigin=""/>

    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
    <!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
 integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
 crossorigin=""></script>

    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% block styles %}
    
    {% endblock %}

</head>
<body>
    <div class="navigation-wrap bg-light start-header start-style">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <nav class="navbar navbar-expand-md navbar-light">
            
              <a class="navbar-brand" href="{% url 'home:index' %}"><img src="{% static 'accounts/img/Logo.png' %}" alt=""></a>	
              
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto py-4 py-md-0">

                  <li class="nav-item pl-md-0 ml-0 ml-md-4">
                    <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                  </li>
                  <li class="nav-item pl-md-0 ml-0 ml-md-4">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Services</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="#">Wedding Venues</a>
                    </div>
                  </li>
                  <li class="nav-item pl-md-0 ml-0 ml-md-4">
                    <a class="nav-link" href="#">Contact</a>
                  </li>
                  

                  {% if user.is_authenticated %}
                  {% if venue_reg == True %}
                      {% if status == False and status2 == False %}
                        <li class="nav-item pl-md-0 ml-0 ml-md-4">
                          <form action="{% url 'accounts:registerAsVenue' %}">
                            <button disabled type="submit" class="regAsVenue">Pending Request</button>
                          </form>
                        </li>
                      {% elif status == True %}
                    <li class="nav-item pl-md-0 ml-0 ml-md-4">
                      <form action="{% url 'venue:VenueEdit' venue_id %}">
                        <button type="submit" class="regAsVenue">Edit Venue
                        </button>
                      </form>
                    </li>
                    {% elif status2 == True %}
                      <li class="nav-item pl-md-0 ml-0 ml-md-4">
                        <form action="{% url 'accounts:registerAsVenue' %}">
                          <button type="submit" class="regAsVenue">Register Venue
                          </button>
                        </form>
                      </li>
                      {% endif %}
                      {% else %}
                      <li class="nav-item pl-md-0 ml-0 ml-md-4">
                        <form action="{% url 'accounts:registerAsVenue' %}">
                          <button type="submit" class="regAsVenue">Register Venue
                          </button>
                        </form>
                      </li>

                
                  {% endif %}


                  <li class="nav-item pl-md-0 ml-0 ml-md-4">
                    <div class="user-prf dropdown-toggle" data-toggle="dropdown"></div>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'accounts:UserProfile' %}">{{request.user}}</a>
                      {% block link %}
                  
                    {% endblock %}
                      <a class="dropdown-item" href="{% url 'booking:Mybookings' %}">My bookings</a>
                      <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>

                    </div>
                  </li>
          
                  {% else %}
                  <li class="nav-item pl-md-0 ml-0 ml-md-4">
                    <form action="{% url 'accounts:loginAsUser' %}">
                      <button type="submit" class="btn-signin">Sign in</button>
                    </form>
                  </li>
                  {% endif %}

                  

                </ul>
              </div>
              
            </nav>		
          </div>
        </div>
      </div>
    </div>

    



  
  <div class="baseCtn">


    {% block body %}

    {% endblock %}
    </div>
    <footer id="footer" class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <img class="mb-4" width="250px" src="{% static 'home/img/Logowhite.png' %}" alt="">
            <p class="text-justify">Venbook.com <i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut nulla bibendum, dapibus diam in, sollicitudin ante. Etiam et leo malesuada arcu aliquet egestas. Duis condimentum neque vel varius auctor. Fusce placerat urna ex, vitae venenatis metus faucibus eu. Cras eu elit turpis. </i></p>
            <p>venbook.helpline@gmail.com</p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick Link</h6>
            <ul class="footer-links">
              <li><a href="{% url 'home:index' %}">Home</a></li>
              <li><a href="">Contact us</a></li>
              <li><a href="">About us</a></li>
              <li><a href="">FAQ</a></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Services</h6>
            <ul class="footer-links">
              <li><a href="">Royal Wedding</a></li>
              <li><a href="">Wedding Party</a></li>
              <li><a href="">Photographer Enquiry</a></li>
              <li><a href="">Makeup Artist Enquiry</a></li>

            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2022 All Rights Reserved by 
         <a href="#">Venbook</a>.
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>   
            </ul>
          </div>
        </div>
      </div>
</footer>

    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script>
      function getToken(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
        }
        const csrftoken = getToken('csrftoken');

    </script>
</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}
Home
{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'home/index.css' %}">

<div class="searchContainer">

    <div class="bg-image">
        <img src="{% static 'home/img/backgroundImg.jpg' %}">
    </div>

    <div class="bg-banner">
    </div>

    <p class="p">Welcome To</p>
    <h1 class="text">Nepal's Top Venue Booking Platform</h1>
    <div class="filter">
        <h5>Filter the perfect venue for your grand event</h5>
        <form method="GET" action="/search">
            <div class="form-group">
                <label class="filter-label" for="inputAddress">Location</label>
                <input type="text" class="form-control" placeholder="1234 Main St" name="location" id="search">
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="filter-label" for="inputEmail4">Date</label>
                    <input type="date" class="form-control" id="inputEmail4" placeholder="Email">
                </div>
                <div class="form-group col-md-6">
                    <label class="filter-label" for="inputState">Events</label>
                    <select id="inputState" class="form-control">
                        <option selected>Choose...</option>
                        <option>Wedding</option>
                        <option>Rice feeding ceremony</option>
                        <option>Bratabanda</option>
                        <option>Bel Bibaha</option>

                    </select>
                </div>
            </div>

            <div align="center">
                <button type="submit" class="btn-search">Search</button>
            </div>
        </form>



    </div>

</div>
<div class="wrapper">
    <div class="box a">
        <img src="{% static 'home/img/1.jpg' %}" alt="">
    </div>
    <div class="box b">
        <h1 class="whyTitle">Why Venbook?</h1>
        <div class="txt1">
            <div>Nepali weddings are always stressful when it comes to pre -wedding, Mehendi ceremony, pre photoshoot,
                clothing, printing wedding cards, and searching venues at the last minute. We understand that a wedding
                is a very special occasion for you and you cannot experiment with the things that can turn into a
                disaster.</div>
            <div>Compare the price and quality of all vendors and select the one that suits your budget. Our mission is
                to help our clients to find the best vendor with up-to-date information under their budget while making
                everyone feel valued, celebrated and relaxed.</div>
        </div>

        <button class="btn">
            Know us better
        </button>
    </div>
    <div class="box c">
        <img src="{% static 'home/img/2.jpg' %}" alt="">
    </div>
    <div class="box d">
        <img src="{% static 'home/img/3.jpg' %}" alt="">
    </div>

</div>

<!-- <footer class="footer">
  <div class="containerfoot">
      <div class="row">
          <div class="footer-col">
              <img src="img/logo.png" alt="" width="240px">
          </div>   
          <div class="footer-col">
              <h4>Know us better</h4>
              <p class="textpara">Lorem quos assumenda ducimus, aliquid maxime voluptatum omnis deleniti obcaecati, consequuntur error vitae voluptatibus. Iste libero esse tenetur quasi blanditiis officia molestias. Ducimus iste sit quia placeat deserunt, nulla praesentium totam atque qui, consequatur deleniti?</p>
          </div>
          <div class="footer-col">
              <h4>Quick links</h4>
              <div class="row">
               <ul>
                   <li><a href="#">Home</a></li>
                   <li><a href="#">Contact us</a></li>
                   <li><a href="#">About us</a></li>
                   <li><a href="#">Newsletter</a></li>
               </ul>
               <ul class="row-1">
                   <li><a href="#">Royal Wedding</a></li>
                   <li><a href="#">Wedding Party</a></li>
                   <li><a href="#">Photographer Enquiry</a></li>
                   <li><a href="#">Makeup Artist Enquiry</a></li>
               </ul> 
           </div>  
          </div> 

          <div class="footer-col">
              <h4>Give us a call!</h4>
              <ul>
                  <li><h5>9800000000</h5></li>
                  <li><h5>info@venbook.com</h5></li>
              </ul>
          </div>
         
      </div>
      <div class="rights">
          <p>Dillibazar, Kathmandu </p>
          <p>2022 Venbook</p>
      </div>
  </div>
</footer> -->



{% endblock %}

home/templates/home/search.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}
Search
{% endblock %}

{% block body %}

{% for post in allPosts %}
<div class="container my-3">
    {% for post in allPosts  %}
    <div
        class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-primary"> {{post.name}}</strong>
            <h3 class="mb-0">{{post.city}}</h3>
            <div class="mb-1 text-muted">{{post.address}}</div>
            <p class="card-text mb-auto">{{post.description| truncatechars:500}}</p>

        </div>
    </div>
</div>

{% endfor %}
</div>

{% endfor %}

{% endblock %}