accounts/urls.py
from django.urls import path

from . import views

app_name='accounts'

urlpatterns= [
    path('registerAsUser', views.registerAsUser, name='registerAsUser'),
    path('loginAsUser', views.loginAsUser, name='loginAsUser'),

    path('userprofile', views.UserProfile, name='UserProfile'),


    path('registerAsVenue', views.registerAsVenue, name='registerAsVenue'),    
    path('venueRegistrationSubmitted', views.venueRegistrationSubmitted, name='venueRegistrationSubmitted'),   

    path('logout', views.logoutUser, name="logout"),
    path("success", views.success, name="success"),

]

home/urls.py
from django.urls import path

from . import views

app_name='home'

urlpatterns= [
    path('', views.index, name='index'),
    path('search', views.search, name="search"),
]

venbook/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.contrib.auth import views as auth_views

from booking import views as bookingView
from accounts import views as accountsView
from venue import views as venueView


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('social_login/', include('allauth.urls')),
    path('venue/',include('venue.urls')),
    path('events/',include('events.urls')),
    path('calender/',include('calender.urls')),
    path('bookings/',include('booking.urls')),

    path('SendRequestUpdate/',bookingView.SendRequestUpdate,name="SendRequestUpdate"),
    path('Cancelbooking/',bookingView.Cancelbooking,name="Cancelbooking"),

    path('AddReview/',venueView.AddReview,name="AddReview"),


    path("EsewaRequestView/", bookingView.EsewaRequestView, name="EsewaRequestView"),


    path("AddUserInfo/", accountsView.AddUserInfo, name="AddUserInfo"),
    path("UpdateUserInfo/", accountsView.UpdateUserInfo, name="UpdateUserInfo"),


    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
        name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), 
        name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),


    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django import forms
from django.db import models
from django.contrib.auth. models import User
from django.conf import settings



# Create your models here.

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True,blank=True)
    phone = models.CharField(max_length=10,null=True,blank=True)
    address = models.CharField(max_length=155,null=True,blank=True)
    gender = models.CharField(
        max_length=6,
        choices=[('Male','Male'),('Female','Female'),('Other','Other')],
        null=True,blank=True
        
    )

    def __str__(self):
        return self.user.email

class UpdateSubscription(models.Model):
     user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1, on_delete=models.CASCADE)
     status = models.BooleanField(default=False)

     def __str__(self):
        return self.user.username


class VenueAccount(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1, on_delete=models.CASCADE)
    name = models.CharField(max_length=155)
    email = models.EmailField(max_length=255)
    pan = models.CharField(max_length=155)
    city = models.CharField(default="Kathmandu", max_length=255)
    address = models.CharField(max_length=255)
    lat = models.FloatField(null=True,blank=True)
    lon = models.FloatField(null=True,blank=True)
    phone = models.CharField(max_length=10)
    event_types = models.ForeignKey(to='events.EventType',on_delete=models.CASCADE)
    description = models.TextField()
    capacity = models.CharField(max_length=155)
    owner_citizenship = models.ImageField(default='default.jpg', upload_to ='owner_citizenship')
    venue_pp = models.ImageField(default='default.jpg', upload_to ='venue_pp')    


    def __str__(self):
        return self.name

    
    def get_venue_account_instance(user_id):
        return VenueAccount.objects.filter(user = user_id)

class is_verified(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    venue_account = models.ForeignKey(VenueAccount, on_delete=models.CASCADE, null=True, blank=True)
    verified = models.BooleanField(default=False)
    unverified = models.BooleanField(default=False)
    unverified_msg = models.TextField(null=True,blank=True)


    def __str__(self):
        return f"{self.venue_account} -- {self.verified}"

class VenueImages(models.Model):
    venue_account = models.ForeignKey(VenueAccount, on_delete=models.CASCADE,null=True,blank=True)
    image = models.ImageField(upload_to ='venue_images')


    def __str__(self):
        return f"{self.venue_account}"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from accounts.models import VenueAccount

from accounts.models import VenueImages
from events.models import EventType

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields =['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class venueRegistrationForm(forms.ModelForm):
    name = forms.CharField(max_length=155,
                            widget= forms.TextInput(
                                attrs={'class':'form-control'}))
    email = forms.EmailField(max_length=155,
                            widget= forms.TextInput(
                                attrs={'class':'form-control'}))
    pan = forms.CharField(max_length=155,
                            widget= forms.TextInput(
                                attrs={'class':'form-control'}))
    city = forms.CharField(max_length=155,
                            widget= forms.TextInput(
                                attrs={'class':'form-control'}))
    address = forms.CharField(max_length=155,
                            widget= forms.TextInput(
                                attrs={'class':'form-control'}))
    phone = forms.CharField(max_length=155,
                            widget= forms.TextInput(
                                attrs={'class':'form-control'}))

    event_types = forms.ModelChoiceField(queryset=EventType.objects.all(),
                                widget=forms.Select(
                                        attrs={'class':'form-control'}))

    description = forms.CharField(max_length=355,
                                widget= forms.Textarea(
                                    attrs={'class':'form-control'}))
    capacity = forms.CharField(max_length=155,
                                widget= forms.TextInput(
                                    attrs={'class':'form-control'}))

    class Meta:
        model = VenueAccount
        fields=[
            "name",
            "email",
            "pan",
            "city",
            "address",
            "phone",
            "event_types",
            "description",
            "capacity",
            "owner_citizenship",
            "venue_pp",           
        ]

class VenueImagesForm(forms.ModelForm):
    image=forms.ImageField(
        label=""
    )

    class Meta:
        model=VenueImages
        fields = ("image",)

accounts/views.py
from django import forms
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.models import User

from accounts.forms import CreateUserForm, VenueImagesForm, venueRegistrationForm
from accounts.models import Account, UpdateSubscription, VenueImages, is_verified

from django.forms import modelformset_factory
from django.views.decorators.csrf import csrf_exempt

from booking.views import is_ajax

# Create your views here.   
def registerAsUser(request):
    form = CreateUserForm()
    if request.user.is_authenticated:
        # return redirect ('home:index')
        print("authenticated")
    else:
        if request.method == 'POST':
            SubStatus = request.POST.get('SubStatus')
            userName = request.POST.get('username')

            form = CreateUserForm(request.POST)

            if form.is_valid():
                print("form is valid")
                form.save()
                print("User Registered")
                
                if SubStatus=="on":
                    status = True
                    print("User has agreed to subscribe")

                    userName = User.objects.get(username=userName)

                    saveSub = UpdateSubscription(user=userName, status=status)
                    saveSub.save()
                else:
                    print("User has not agreed to subscribe")
                    
                return redirect('accounts:success') 
            else:
                context ={
                    'form':form
                }
                return render(request, 'accounts/register.html',context)



              
        else:
            form = CreateUserForm()

    context ={
        'form':form
    }
    return render(request, 'accounts/register.html',context)

def success(request): 
    return render(request, "accounts/success.htm")

@csrf_exempt
def loginAsUser(request):
    if request.user.is_authenticated:
        return redirect ('home:index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request,username=username, password=password)

            if username and password !="":
                if user is not None:
                    login(request,user)
                    return redirect('home:index')

                else:
                    print('Username or password is incorrect')
            else:
                print('Enter Username or password is incorrect')

    return render(request, "accounts/login.html")


def logoutUser(request):
    logout(request)
    return redirect('home:index')


def registerAsVenue(request):
    form = venueRegistrationForm()
    venueImagesformset = modelformset_factory(VenueImages,
                                        form=VenueImagesForm,extra=4)

    if request.method == "POST":
        form = venueRegistrationForm(request.POST, request.FILES)
        # files = request.FILES.getlist("image")
        venueImages = venueImagesformset(request.POST, request.FILES, queryset=VenueImages.objects.none())
        
        if form.is_valid() and venueImages.is_valid():
            f= form.save()
            f.user = request.user
            f.save()

            is_verified.objects.create(user=request.user, venue_account=f, verified=False)
            
            for imageForm in venueImages.cleaned_data:
                if imageForm:
                    image = imageForm['image']
                    photo = VenueImages(venue_account=f, image=image)
                    photo.save()
                else:
                    raise forms.ValidationError("Add Photos")

            return redirect("accounts:venueRegistrationSubmitted")
        else:
            return render(request,'accounts/venueregistration.html', {
        'form':form,
        'venueImages':venueImages,
        })
        
    context ={
        'form':form,
        'venueImages': venueImagesformset(queryset=VenueImages.objects.none()),
        }

    return render(request,'accounts/venueregistration.html', context)

def venueRegistrationSubmitted(request):
    return render(request, 'accounts/venueregistration_submitted.html')
        
def UserProfile(request):
    userprf = False
    try:
        userInfo = Account.objects.get(user=request.user)
        userprf = True
    except Account.DoesNotExist:
        userInfo = None

    context = {
        'userInfo':userInfo,
        'userprf':userprf,
    }
    return render(request, 'accounts/user_profile.html',context)

def AddUserInfo(request):
    if is_ajax(request=request):
        dob = request.POST.get('dob')
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        gender = request.POST.get('gender')
        print(dob,address,phone,gender)

        f = Account.objects.create(user=request.user, dob=dob, phone=phone, address=address, gender=gender)
        f.save()
        
        return JsonResponse("Success",safe=False)

def UpdateUserInfo(request):
    if is_ajax(request=request):
        print("Updating")
        userInfo = Account.objects.get(user=request.user)

        dob = request.POST.get('dob')
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        gender = request.POST.get('gender')

        print(dob,address,phone,gender)

        updateStatus = False

        userInfo.dob=dob 
        userInfo.phone=phone
        userInfo.address=address
        userInfo.gender = gender

        userInfo.save()

        updateStatus=True

        return JsonResponse(updateStatus,safe=False)

accounts/templates/accounts/login.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE html> 
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'accounts/login.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
</head>

<body>

    <div class="loginpage">
        <form class="login" method="POST">
            {% csrf_token %}
            <div align="center">
                <img src="{% static 'accounts/img/Logo.png' %}" alt="venbook logo" width="240" height="100%">
            </div>
            <h2>Login to your account</h2>
            <div class="underline">
                <hr>
            </div>
            <div class="form-group">
                <label for="email">Username</label>
                <div class="input-group">
                    <input name="username" type="text" id="email" placeholder="testuser">
                </div>
            </div>
            <div class="form-group">
                <label for="email">Password</label>
                <div class="input-group-pass">
                    <input name="password" type="password" id="password" placeholder="•••••••••••">
                </div>
            </div>
            <div class="fpass"><a href="{% url 'reset_password' %}">Forget Password?</a></div>
            <div align="center">
                <button type="submit" class="btn-signin">Sign in</button>
            </div>
            <div class="or">
                <div></div>
                <p>or</p>
                <div></div>
            </div>
            <div align="center">
                <div class='g-sign-in-button'>
                    <div class=content-wrapper>
                        <div class='logo-wrapper'>
                            <img
                                src='https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-suite-everything-you-need-know-about-google-newest-0.png'>
                        </div>
                        <span class='text-container'>
                            <a href="{% provider_login_url 'google' %}">Sign in with google</a>
                        </span>
                    </div>
                </div> 
            </div>

            <p class="signup">Don't have an account? <a style="font-weight: 600; color: rgb(254, 27, 27);"
                    href="{% url 'accounts:registerAsUser' %}">Register</a></p>
        </form>

    </div>

</body>

</html>

accounts/templates/accounts/password_reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>forgotpassword</title>
    <link rel="stylesheet" href="{% static 'accounts/passwordreset.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'accounts/forgotpassword.css' %}"> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
</head>
    
   <body>
       
    <form class="fgt-form" method="post">
        {% csrf_token %}
        <div align="center">
            <img src="{% static 'accounts/img/Logo.png' %}" alt="venbook logo" width="240" height="100%">
        </div>
        <br><br><br>
        <h1 class="forgt-text">Forgot your Password?</h1>


        <div class="txtb">
            <p style="font-size: 20px; text-align:center; font-weight: 500;">Enter your email address</p>
            <br>
            {{form}}
            <span data-placeholder="E-mail"></span>
        </div>

        <br> 
        <center>

            <input type="submit" class="logbtn" name="Send email" value="Submit" style="font-size: 15px; color:rgb(63, 63, 63);">
        </center>
       
        <div class="forgt-btn">
         <label >*A reset link will be sent to your email</label>
        </div>

    </form>



</body>

</html>

accounts/templates/accounts/password_reset_done.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>forgotpassword</title>
    <link rel="stylesheet" href="{% static 'accounts/passwordreset.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'accounts/forgotpassword.css' %}"> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
</head>
    
   <body>
       
    <div style="width: 60%; height: auto;" class="fgt-form">
        <div align="center">
            <img src="{% static 'accounts/img/Logo.png' %}" alt="venbook logo" width="200" height="100%">
        </div>
        <br>
        <center>
            <h6 style="font-size: 16px; margin-top: 60px; font-family:Arial, Helvetica, sans-serif; color: #2c2c2c; line-height: 2;">
                Your password has been set. You may go ahead and log in now.
            </h6>
        </center>

        <div align="center">
            <form action="{% url 'accounts:loginAsUser' %}">
                <button type="submit" class="logbtn">Redirect to login</button>
            </form>

            </div>
        

        </div>



</body>

</html>

accounts/templates/accounts/password_reset_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>forgotpassword</title>
    <link rel="stylesheet" href="{% static 'accounts/passwordreset.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'accounts/forgotpassword.css' %}"> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
</head>
    
   <body>
       
    <form class="fgt-form" method="post">
        {% csrf_token %}
        <div align="center">
            <img src="{% static 'accounts/img/Logo.png' %}" alt="venbook logo" width="200" height="100%">
        </div>
        <br><br><br>
        <h1 class="forgt-text">Create New Password</h1>


        <div class="txtb">
            <br>
            {{form}}
        </div>

        <br> 
        <input type="submit" class="logbtn" name="Send email" value="Submit" style="font-size: 15px; color:white;">
       
        <div class="forgt-btn">
         <label style="font-style: italic; font-weight: bold;">*A reset link will be sent to your email</label>
        </div>

    </form>



</body>

</html>

accounts/templates/accounts/password_reset_sent.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>forgotpassword</title>
    <link rel="stylesheet" href="{% static 'accounts/passwordreset.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'accounts/forgotpassword.css' %}"> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
</head>
    
   <body>
       
    <form style="width: 60%; height: auto;" action="index.html" class="fgt-form">
        {% csrf_token %}
        <div align="center">
            <img src="{% static 'accounts/img/Logo.png' %}" alt="venbook logo" width="200" height="100%">
        </div>
        <br>
        <center>
            <h6 style="font-size: 16px; margin-top: 60px; font-family:Arial, Helvetica, sans-serif; color: #2c2c2c; line-height: 2;">
                We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
                <br>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
            </h6>
        </center>
        

    </form>



</body>

</html>

accounts/templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> Create an account </title>
    <link rel="stylesheet" href="{% static 'accounts/register.css' %}">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
    <div class="logo">
      <img src="{% static 'accounts/img/Logo.png' %}" alt="venbook logo" width="220" height="100%">
    </div><br>
    <div class="title">Create an Account</div>

    <div class="content">
      <form class="form" method="POST">
        {% csrf_token %}
        <div class="user-details">
          <div class="input-box">
            <span class="details">First Name</span>
            {{form.first_name}}
          </div>
          <div class="input-box">
            <span class="details">Last Name</span>
            {{form.last_name}}
          </div>
          <div class="input-box">
            <span class="details">Username</span>
            {{form.username}}
          </div>
          <div class="input-box">
            <span class="details">Email</span>
            {{form.email}}
          </div>
          <div class="input-box">
            <span class="details">Password</span>
            {{form.password1}}
          </div>
          <div class="input-box">
            <span class="details">Confirm Password</span>
            {{form.password2}}
          </div>
          
        </div>
        <div class="send-updates">
          <input type="radio" name="SubStatus" id="dot-4">
          <label for="dot-4">
          <span class="dot four"></span>
          <span class="updates">Send me venue's and new venue updates</span>
        </label>
        </div>
        {% if form.errors %}
                    <div class="alert alert-danger">
                        {{ form.errors }}
                    </div>
        {% endif %}
        <!-- <div class="gender-details">
          <input type="radio" name="gender" id="dot-1">
          <input type="radio" name="gender" id="dot-2">
          <input type="radio" name="gender" id="dot-3">
          
          <span class="gender-title">Gender</span>
          <div class="category">
            <label for="dot-1">
            <span class="dot one"></span>
            <span class="gender">Male</span>
          </label>
          <label for="dot-2">
            <span class="dot two"></span>
            <span class="gender">Female</span>
          </label>
          <label for="dot-3">
            <span class="dot three"></span>
            <span class="gender">Other</span>
            </label>
          </div><br>
          
        </div> -->
        <div class="button">
          <input type="submit" value="Sign up">
        </div>
        <div style="text-align: center;">
          <p class="signin">Already have an account? <a style="font-weight: 600; color: rgb(254, 27, 27);" href="{% url 'accounts:loginAsUser' %}">Login</a></p>
        </div>
      </form>
    </div>
  </div>
  <script>
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='FirstName';
		form_fields[2].placeholder='LastName';
		form_fields[3].placeholder='Username';
		form_fields[4].placeholder='Email';
		form_fields[5].placeholder='Password';
		form_fields[6].placeholder='Confirm Password';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

accounts/templates/accounts/success.htm
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #ebe9e9;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #abdd61;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }

      .login-btn{
        margin-top: 40px;
        width: 20%;
        border-radius: 50px;
        background-color: #f3d216;
        border: 0;
        padding: 15px;
        font-size: 0.9vw;
        color: #202020;
        font-weight: bold;
        cursor: pointer;
      }
      .login-btn:hover,
      .login-btn:focus {
        box-shadow: 0 1em 1em -0.4em grey;
        transform: translateY(-0.25em);
        transition: 0.3s;
      }
    </style>
    <body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>User Account Registered</h1> 
        <p>Please proceed to login page to continue</p>
        <a href="{% url 'accounts:loginAsUser' %}">
            <button class="login-btn">
                Login
            </button>
        </a>

      </div>
    </body>
</html>

accounts/templates/accounts/venueregistration_submitted.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial scale=1.0">
    <title></title>
    <!-- <link rel="stylesheet" href="venueregistration_submitted.css"> -->
    <link rel="stylesheet" href="{% static 'accounts/venueregistration_submitted.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
</head>
    
   <body>
    <form action="{% url 'home:index' %}" class="form-submit">
        <div align="center">
            <img src="{% static 'accounts/img/Logo.png' %}" alt="venbook logo" width="200" height="100%">
        </div>
        <br>

        <div class="txta">
            <p style="text-align:center; font-weight: 500;">Your venue registration form has been submitted for verification.</p>
        </div>

        <div class="txtb">
            <p style="text-align:center; font-weight: 500;">We shall inform you through your email once the verification process is completed.</p>
            <br>
            <br>
        </div>

        <br> 
            <button type="submit" class="direct" style="font-size: 15px; color:rgb(22, 22, 21);">Redirect to home page</button>

    </form>

</body>

</html>