calender/urls.py
from django.urls import path

from . import views

app_name='calender'

urlpatterns= [
    path('', views.viewCalender, name='viewCalender'),

]

home/urls.py
from django.urls import path

from . import views

app_name='home'

urlpatterns= [
    path('', views.index, name='index'),
    path('search', views.search, name="search"),
]

venbook/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.contrib.auth import views as auth_views

from booking import views as bookingView
from accounts import views as accountsView
from venue import views as venueView


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('social_login/', include('allauth.urls')),
    path('venue/',include('venue.urls')),
    path('events/',include('events.urls')),
    path('calender/',include('calender.urls')),
    path('bookings/',include('booking.urls')),

    path('SendRequestUpdate/',bookingView.SendRequestUpdate,name="SendRequestUpdate"),
    path('Cancelbooking/',bookingView.Cancelbooking,name="Cancelbooking"),

    path('AddReview/',venueView.AddReview,name="AddReview"),


    path("EsewaRequestView/", bookingView.EsewaRequestView, name="EsewaRequestView"),


    path("AddUserInfo/", accountsView.AddUserInfo, name="AddUserInfo"),
    path("UpdateUserInfo/", accountsView.UpdateUserInfo, name="UpdateUserInfo"),


    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
        name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), 
        name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),


    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

venue/urls.py
from django.urls import include, path

from . import views


app_name='venue'


urlpatterns= [
    path('venuedisplay', views.VenueDisplay, name='VenueDisplay'),
    path('dashboard/<int:id>', views.VenueEdit, name='VenueEdit'),
    path('updatevenueprice/', views.VenuePriceUpdate, name='VenuePriceUpdate'),
    path('updatevenuedesc/<int:id>', views.VenueDescUpdate, name='VenueDescUpdate'),
    path('venuedetail/<int:id>',views.VenueDetail,name="VenueDetail"),
    path('booking-request/',views.BookingRequest,name="BookingRequest"),
]

venue/models.py
from operator import mod
from unicodedata import name
from django.conf import settings
from django.db import models
from django.forms import ModelForm, TextInput
from accounts.models import VenueAccount

from multiselectfield import MultiSelectField

# Create your models here.
class VenuePricing(models.Model):
    venue_account = models.ForeignKey(VenueAccount, on_delete=models.CASCADE,null=True,blank=True)
    min_people = models.IntegerField(null=True,blank=True)
    mid_people = models.IntegerField(null=True,blank=True)
    max_people = models.IntegerField(null=True,blank=True)
    # Additional Charges
    dj_price = models.IntegerField(null=True,blank=True)
    decoration = models.BooleanField(default=False,null=True,blank=True)
    projectors = models.IntegerField(null=True,blank=True)
    

    def __str__(self):
        return self.venue_account.name

    def get_venue_pricing(venue_id):
        return VenuePricing.objects.filter(venue_account = venue_id)[0]

class VenueFacilitiesServices(models.Model):
    venue_choices = (
    ('DJ Service', 'DJ Service'),
    ('Parking Space', 'Parking Space' ),
    ('Customized decoration', 'Customized decoration'),
    ('Projectors', 'Projectors'),
    ('Changing Room', 'Changing Room'),
    ('Makeup Service', 'Makeup Service'),
    ('Fireworks', 'Fireworks'),
    ('Live Music', 'Live Music'),)
    venue_account = models.ForeignKey(VenueAccount, on_delete=models.CASCADE,null=True,blank=True)
    choice =MultiSelectField(choices=venue_choices)


class VenueReview(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    venue_account = models.ForeignKey(VenueAccount, on_delete=models.CASCADE, null=True, blank=True)
    comment = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

venue/forms.py
from cgitb import text
from django import forms
from venue.models import VenuePricing

class pricing(forms.ModelForm):
    min_people = forms.IntegerField(
                    widget= forms.NumberInput(attrs={'min': '0','placeholder': '0','class':'priceInput'}))
    mid_people = forms.IntegerField(
                    widget= forms.NumberInput(attrs={'min': '0','placeholder': '0','class':'priceInput'}))
    max_people = forms.IntegerField(
                    widget= forms.NumberInput(attrs={'min': '0','placeholder': '0','class':'priceInput'}))
    dj_price = forms.IntegerField(
                    widget= forms.NumberInput(attrs={'min': '0','placeholder': '0','class':'priceInput'}))
    decoration = forms.BooleanField(
                    widget= forms.CheckboxInput(attrs={'class':'priceInput'}))        
    projectors = forms.IntegerField(
                    widget= forms.NumberInput(attrs={'min': '0','placeholder': '0','class':'priceInput'}))
    class Meta:
        model = VenuePricing
        fields=[
            "venue_account",
            "min_people",
            "mid_people",
            "max_people",
            "dj_price",
            "decoration",
            "projectors",
    ]

venue/views.py
from multiprocessing import context
from xml.dom.expatbuilder import Rejecter
from django.conf import settings
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render

from accounts.models import VenueAccount
from booking.views import is_ajax
from events.forms import OutEventInfoForm, OutEventsUserInfoForm, VenbookEventInfoForm
from events.models import OutEventInfo, OutEventsUserInfo, VenbookEventInfo, VenbookEventRequest
from venue.forms import pricing
from venue.models import VenueFacilitiesServices, VenuePricing, VenueReview
from django.contrib import messages

import datetime

from django.core.mail import send_mail

# Create your views here.


def PriceExistStatus(id):
    price_exist_status = False

    if VenuePricing.objects.filter(venue_account=id).exists():
        price_exist_status = True
    else:
        price_exist_status = False

    return price_exist_status


def VenuePriceData(id):
    venueData = None
    if VenuePricing.objects.filter(venue_account=id).exists():
        venueData = VenuePricing.objects.get(venue_account=id)
    return venueData


def VenueEdit(request, id):
    weekagodate = datetime.date.today() + datetime.timedelta(days=7)
    venue_id = VenueAccount.get_venue_account_instance(request.user)[0]
    venue_instance = VenueAccount.objects.get(id=id)

    eventupcoming=[]
    # for upcoming events
    for i in VenbookEventRequest.objects.filter(venue_event_info__venue_account = venue_instance, accept=True, reject=False, cancelled = False):
        if i.venue_event_info.event_date > datetime.date.today() and i.venue_event_info.event_date < weekagodate:
            eventupcoming.append(i)

    if id == venue_id.id:
        form = pricing()
        data = {'venue_account': id}
        eventForm = OutEventInfoForm(initial=data)
        eventUserForm = OutEventsUserInfoForm(initial=data)

        venue_instance = VenueAccount.objects.get(id=id)

        if ('addnewpriceBtn' in request.POST):
            form = pricing(request.POST)
            if form.is_valid():
                f = form.save()
                f.venue_account = venue_instance
                f.save()

        elif ('createeventBtn' in request.POST):
            eventForm = OutEventInfoForm(request.POST)
            eventUserForm = OutEventsUserInfoForm(request.POST)
            if eventForm.is_valid() and eventUserForm.is_valid():
                a = eventForm.save()
                a.save()

                first_name = request.POST.get('first_name')
                last_name = request.POST.get('last_name')
                email = request.POST.get('email')
                phone = request.POST.get('phone')

                OutEventsUserInfoData = OutEventsUserInfo.objects.create(
                    event_info=a, first_name=first_name, last_name=last_name, email=email, phone=phone)
                OutEventsUserInfoData.save()

                return redirect('venue:VenueEdit', id=id)

            else:
                return render(request, 'venue/editvenue.html',
                    {
                        'venue_instance': venue_instance,
                        'price_exist_status': PriceExistStatus(id),
                        'VenuePriceData':VenuePriceData(id),
                        'form':form,
                        'eventForm':eventForm,
                        'eventUserForm':eventUserForm,
                        'eventupcoming': len(eventupcoming),
                        'outevent_exists':outevent_exists,
                        'outvenbookEvent_list':outvenbookEvent_list,

                        'bookedEventCount':VenbookEventRequest.count_booked_event(request),
                        'RequestEventCount':VenbookEventRequest.count_event_request(request),
                        'DeclinedRequestEventCount':VenbookEventRequest.count_declined_request(request),
                    })

        event_exists = False
        if VenbookEventRequest.objects.filter(venue_event_info__venue_account=venue_instance, accept=True, reject=False, cancelled = False).exists():
            event_exists = True
            venbookEvent_list = []

            venbooklist = VenbookEventRequest.objects.filter(
                venue_event_info__venue_account=venue_instance, accept=True, reject=False, cancelled = False).order_by('-venue_event_info__registered_at')

            for i in venbooklist:
                venbookEvent_list.append(i)

        else:
            venbookEvent_list = []
            event_exists = False

        outevent_exists = False
        if OutEventsUserInfo.objects.filter(event_info__venue_account = venue_instance).exists():
            outevent_exists = True
            outvenbookEvent_list = []

            outvenbooklist = OutEventsUserInfo.objects.filter(event_info__venue_account = venue_instance).order_by('-event_info__registered_at')

            for i in outvenbooklist:
                outvenbookEvent_list.append(i)

        else:
            outvenbookEvent_list =[]
            outevent_exists = False
                              
        context ={
            'venue_instance':venue_instance,
            'price_exist_status': PriceExistStatus(id),
            'VenuePriceData':VenuePriceData(id),
            'form':form,
            'eventForm':eventForm,
            'eventUserForm':eventUserForm,
            'outevent_exists':outevent_exists,
            'outvenbookEvent_list':outvenbookEvent_list,
            'event_exists':event_exists,
            'venbookEvent_list':venbookEvent_list,
            'eventupcoming': len(eventupcoming),

            'bookedEventCount':VenbookEventRequest.count_booked_event(request),
            'RequestEventCount':VenbookEventRequest.count_event_request(request),
            'DeclinedRequestEventCount':VenbookEventRequest.count_declined_request(request),
            }

        return render(request, 'venue/editvenue.html', context)
    else:
        raise Http404


def VenuePriceUpdate(request):
    if request.method == "POST" and 'updatenewprice':
        venue_id = request.POST.get('venue_id')
        min_people = request.POST.get('min-people')
        mid_people = request.POST.get('mid-people')
        max_people = request.POST.get('max-people')
        dj_price = request.POST.get('dj_price')
        decoration = request.POST.get('decoration')
        projectors = request.POST.get('projectors')

        venue_price_instance = VenuePricing.objects.get(venue_account=venue_id)
        venue_price_instance.min_people = min_people
        venue_price_instance.mid_people = mid_people
        venue_price_instance.max_people = max_people

        if decoration == "on":
            venue_price_instance.decoration = True
        else:
            venue_price_instance.decoration = False

        venue_price_instance.dj_price = dj_price
        venue_price_instance.projectors = projectors
        venue_price_instance.save()

    return redirect('venue:VenueEdit', id=venue_id)


def VenueDescUpdate(request, id):
    if request.method == "POST" and 'updatedesc':
        venue_acc_instance = VenueAccount.objects.get(user=request.user)

        venue_desc = request.POST.get('venue_description')
        venue_acc_instance.description = venue_desc
        venue_acc_instance.save()
    return redirect('venue:VenueEdit', id=id)


def VenueDetail(request, id):
# Send email to customer
    def send_booking_request_email(email, name, eventname, date):
        send_mail(
            subject='Venbook Event Booking Request',
            message=f'Hello {name}, The event booking request for {eventname} on {date} has been sent to venue for confirmation. You shall be notified regarding the confirmation status of your request through email. Thank you!',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[email]
        )

# Send email to venue
    def send_booking_request_email_to_venue(email, vname, name, eventname, date):
        send_mail(
            subject='Venbook Event Booking Request',
            message=f'Hello {vname}, You have received a new event booking request from {name} with event name {eventname} on {date}. Please update the request status through Booking Request Page. The status shall be informed to respective customer. Thank you!',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[email]
        )
    venue_instance = VenueAccount.objects.get(id=id)
    venue_services = None
    venue_price = None

    reviews = VenueReview.objects.filter(venue_account=venue_instance)

    if VenuePricing.objects.filter(venue_account=venue_instance).exists():
        venue_price = VenuePricing.objects.filter(
            venue_account=venue_instance)[0]

    if VenueFacilitiesServices.objects.filter(venue_account=venue_instance).exists():
        venue_services = VenueFacilitiesServices.objects.filter(
            venue_account=venue_instance)[0]

    if request.user.is_authenticated:
        data = {'venue_account': id,
                'full_name': request.user.first_name + " " + request.user.last_name,
                'email': request.user.email}
    else:
        data = {'venue_account': " ",
                'full_name': " ",
                'email': " "}
    EventBookForm = VenbookEventInfoForm(initial=data)

    # For calender Events
    allevents = []

    outevents = OutEventInfo.get_event_of_venue(venue_instance)
    venbookevents = VenbookEventRequest.objects.filter(venue_event_info__venue_account=venue_instance, accept=True, reject=False, cancelled = False)
    for i in outevents:
        allevents.append(i)

    for i in venbookevents:
        allevents.append(i)

    if (request.method == "POST"):
        EventBookForm = VenbookEventInfoForm(request.POST)

        if EventBookForm.is_valid():
            print("form Valid")
            e = EventBookForm.save()
            e.user = request.user
            e.save()

venue/templates/venue/booking-request.html
{% extends 'home/base.html' %}
{% load static %}

{% block link %}
<a class="dropdown-item" href="{% url 'calender:viewCalender' %}">Calender</a>  
<a class="dropdown-item" href="{% url 'venue:BookingRequest' %}">Booking Request</a>  

{% endblock %}

{% block title %}
    My booking
{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'venue/bookingReq.css' %}">
<script type="text/javascript" src="{% static 'venue/jquery-3.6.0.js' %}"></script> 

<div id="afterStatusDiv" class="afterstatusDiv">         
</div>

<div style="min-height: 100vh; padding: 30px;">
    <h1 class="heading">Booking Requests</h1>
    <div id="msgChk" class="msg-box d-none update-info alert alert-info alert-dismissible fade show" role="alert">
        <p class="msg p-0 m-0">Please wait while we update the booking request</p> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <table class="content-table">
        <form name="requestUpdateForm" action="">
        <thead>
          <tr>
            <th class="tableHeading">Event Date</th>
            <th class="tableHeading">Customer Info</th>
            <th class="tableHeading">Event type</th>
            <th class="tableHeading">Guests</th>
            <th class="tableHeading">Event Details</th> 
            <th class="tableHeading">Status</th>
            <th class="tableHeading">Action</th>
          </tr>
        </thead>
        <tbody>
            {% for request in requests %}
          <tr>
            <td class="center-align"><div class="tableHeadingMobile">Event Date</div> {{request.venue_event_info.event_date}}</td>
            <td>

                <div class="tableHeadingMobile" style="margin-bottom: 10px;">Name</div> {{request.venue_event_info.full_name}} <br> 

                <div class="tableHeadingMobile" style="margin-bottom: 10px;">Email</div> {{request.venue_event_info.email}} <br> 

                <div class="tableHeadingMobile" style="margin-bottom: 2px;">Contact</div> {{request.venue_event_info.phone}} <br> 

            </td>
            <td class="center-align"><div class="tableHeadingMobile">Event Type</div> {{request.venue_event_info.event_type}}</td>
            <td class="center-align"><div class="tableHeadingMobile">Guests</div> {{request.venue_event_info.people}}</td>
            <td><div class="tableHeadingMobile">Event Details</div> {{request.venue_event_info.event_details}}</td>
            <td class="center-align">

                {% if request.cancelled == True %}
                    <div id="statusCtn">
                        <div class="tableHeadingMobile">Status</div> <strong style="color: red;">Canceled</strong>
                    </div>
                {% else %}
                        {% if request.accept == False and request.reject == False %}
                        <div>


                            <div id="statusCtn">
                                <div class="tableHeadingMobile">Status</div> <strong style="color: grey;">Pending</strong>
                            </div>


                        </div>
                            {% elif request.accept == True and request.reject == False %}
                                <div>
                                    <div id="statusCtn">
                                        <div class="tableHeadingMobile">Status</div> <strong style="color: rgb(0, 187, 0);">Accepted</strong>
                                    </div>
                
                                </div>
            
                                
                            {% elif request.accept == False and request.reject == True %}
                            <div>

                                <div id="statusCtn">
                                    <div class="tableHeadingMobile">Status</div> <strong style="color: red;">Declined</strong>
                                </div>
                

                            </div>
            
            
                        {% endif %}
                {% endif %}
            
            </td>     
            <td class="center-align">
                {% if request.cancelled == True %}
                    <div id="actionBtnCtn">
                        <button class='btn btn-danger btn-sm' disabled>Canceled</button>
                    </div>
                {% else %}

                        {% if request.accept == False and request.reject == False %}
                    <div>
                        <div id="AfterStatus"></div>
                        
                        <div id="RequestUpdateRadio" >
                            <input type="radio" id="accept" name="status" value=True>
                            <label for="accept">Accept</label>
                            <input type="radio" id="reject" name="status" value=False>
                            <label for="reject">Reject</label>
                        </div>
                        <div id="actionBtnCtn">
                            
                            <button class='btn btn-success mb-4 btn-sm' id="{{request.id}}" onclick="sendRequestUpdate(event, {{request.id}})">Send Request update</button>
                        </div>
                    </div>
                        {% elif request.accept == True and request.reject == False %}
                            <div>
                                <div id="AfterStatus">
                                    <p>Advance Quotation: Nrs {{request.advance_quotation}}</p>
                                </div>
                                
                            
                                <div id="actionBtnCtn">
                                    {% if request.advance_payment_received %}
                                        <button class='btn btn-success mb-4 btn-sm' disabled>Advance Payment Received</button>
                                    {% else %}
                                        <button class='btn btn-warning mb-4 btn-sm' disabled>Awaiting Payment</button>
                                    {% endif%}
                                </div>
                            </div>
        
                            
                        {% elif request.accept == False and request.reject == True %}
                        <div>
                            <div id="AfterStatus">
                                Reject message:<br/><textarea id='reject_reason' name='reject_reason' id='' cols='30' disabled>{{request.reject_reason}}</textarea><br/>
                            </div>
                            
                            <div id="actionBtnCtn">
                                <button class='btn btn-danger mb-4'>Delete</button>
                            </div>
                        </div>
    
                        {% endif %}
                {% endif %}
            </td>
          </tr>
          {% endfor %}
        </form>
        </tbody>
      </table>
</div>
 
<script>   
    // For updating the request
    function addInputField()
    {
        document.getElementById('afterStatusDiv').innerHTML= ""

        document.getElementsByClassName("afterstatusDiv")[0].style.height = "150px"
        document.getElementsByClassName("afterstatusDiv")[0].style.padding = "20px"

        document.getElementById('afterStatusDiv').innerHTML += "Advance Quotation:<br/> <input type='number' id='Newquotation' name='quotation' value='' /><br/>";
        
    }
    function addTextField()
    {
        document.getElementById('afterStatusDiv').innerHTML= ""
        document.getElementsByClassName("afterstatusDiv")[0].style.height = "335px"
        
        document.getElementById('afterStatusDiv').innerHTML += "Reject message:<br/><textarea  name='reject_reason' id='Newreject_reason' cols='30' rows='10'></textarea><br/>";
        
    }
    var radios = document.forms["requestUpdateForm"].elements["status"];

    
    
    var RequestStatus = "False"
    for(var i = 0, max = radios.length; i < max; i++) {
        radios[i].onclick = function() {
            console.log(i)
            if(this.value == "True"){
                RequestStatus = "True"
                addInputField()
            }
            else if(this.value == "False"){
                RequestStatus = "False"
                addTextField()
            }
        }
    }
    
    
    // var CurrentClickedBookingID = ""

    // function returnId(e,id){
    //     e.preventDefault();
    //     CurrentClickedBookingID =  id
    // }
    
    function sendRequestUpdate(e,id){
        e.preventDefault();
        console.log(id)
        $('#' + id).prop('disabled', true)
        $('#' + id).removeClass("btn-success");
        $('#' + id).addClass("btn-info");
        $('#' + id).html("Please wait while we process the booking status");
        document.getElementsByClassName("afterstatusDiv")[0].style.height = "0px"
        $('.update-info').removeClass('d-none')
        $.ajax({
                type : "POST", 
                url: "{% url 'SendRequestUpdate' %}",
                data: {
                 id : id,
                 status : RequestStatus,
                 quotation : $('#Newquotation').val(),
                 reason : $('#Newreject_reason').val(),
                 csrfmiddlewaretoken: csrftoken,
                 dataType: "json",
                },
                
                success: function(data){
                   console.log(data) /* response message */
                   alert("Booking Request Updated. Respective customer have been informed. Thank you for your patience!")
                   location.reload()
                },
         
                failure: function() {
                    console.log("failed")
                    
                }
         
         
            });

    }
    
</script>
{% endblock %}